name: .NET 8 CI

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Homies.sln

      # 4. Build project
      - name: Build project
        run: dotnet build Homies.sln --configuration Release --no-restore

      # 5. Run tests
      - name: Run tests
        run: dotnet test Homies.sln --no-build --verbosity normal

      # 6. Optional: Upload test results
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: '**/TestResults/*.xml'
